version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g wrangler
  pre_build:
    commands:
      - cd www.suprasy.com
      - npm install --force
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - CLOUDFLARE_ACCOUNT_ID=${CLOUDFLARE_ACCOUNT_ID} CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN} wrangler pages deploy ./public --project-name=suprasy-com --branch=main --commit-dirty=true

